lang_dict = {
    'af': 'afrikaans',
    'sq': 'albanian',
    'am': 'amharic',
    'ar': 'arabic',
    'hy': 'armenian',
    'az': 'azerbaijani',
    'eu': 'basque',
    'be': 'belarusian',
    'bn': 'bengali',
    'bs': 'bosnian',
    'bg': 'bulgarian',
    'ca': 'catalan',
    'ceb': 'cebuano',
    'ny': 'chichewa',
    'zh-cn': 'chinese',
    'co': 'corsican',
    'hr': 'croatian',
    'cs': 'czech',
    'da': 'danish',
    'nl': 'dutch',
    'en': 'english',
    'eo': 'esperanto',
    'et': 'estonian',
    'tl': 'filipino',
    'fi': 'finnish',
    'fr': 'french',
    'fy': 'frisian',
    'gl': 'galician',
    'ka': 'georgian',
    'de': 'german',
    'el': 'greek',
    'gu': 'gujarati',
    'ht': 'haitian creole',
    'ha': 'hausa',
    'haw': 'hawaiian',
    'he': 'hebrew',
    'hi': 'hindi',
    'hmn': 'hmong',
    'hu': 'hungarian',
    'is': 'icelandic',
    'ig': 'igbo',
    'id': 'indonesian',
    'ga': 'irish',
    'it': 'italian',
    'ja': 'japanese',
    'jw': 'javanese',
    'kn': 'kannada',
    'kk': 'kazakh',
    'km': 'khmer',
    'ko': 'korean',
    'ku': 'kurdish', #kurmanji dialect
    'ky': 'kyrgyz',
    'lo': 'lao',
    'la': 'latin',
    'lv': 'latvian',
    'lt': 'lithuanian',
    'lb': 'luxembourgish',
    'mk': 'macedonian',
    'mg': 'malagasy',
    'ms': 'malay',
    'ml': 'malayalam',
    'mt': 'maltese',
    'mi': 'maori',
    'mr': 'marathi',
    'mn': 'mongolian',
    'my': 'burmese',
    'ne': 'nepali',
    'no': 'norwegian',
    'or': 'odia',
    'ps': 'pashto',
    'fa': 'persian',
    'pl': 'polish',
    'pt': 'portuguese',
    'pa': 'punjabi',
    'ro': 'romanian',
    'ru': 'russian',
    'sm': 'samoan',
    'gd': 'scots gaelic',
    'sr': 'serbian',
    'st': 'sesotho',
    'sn': 'shona',
    'sd': 'sindhi',
    'si': 'sinhala',
    'sk': 'slovak',
    'sl': 'slovenian',
    'so': 'somali',
    'es': 'spanish',
    'su': 'sundanese',
    'sw': 'swahili',
    'sv': 'swedish',
    'tg': 'tajik',
    'ta': 'tamil',
    'te': 'telugu',
    'th': 'thai',
    'tr': 'turkish',
    'uk': 'ukrainian',
    'ur': 'urdu',
    'ug': 'uyghur',
    'uz': 'uzbek',
    'vi': 'vietnamese',
    'cy': 'welsh',
    'xh': 'xhosa',
    'yi': 'yiddish',
    'yo': 'yoruba',
    'zu': 'zulu',
}
inv_lang_dict = {v: k for k, v in lang_dict.items()}
lang_fam_dict = {
    'af': 'Germanic (Indo-European)', #'afrikaans',
    'sq': 'Other Indo-European', #'albanian',
    'am': 'Semitic (Afro-Asiatic)', #'amharic',
    'ar': 'Semitic (Afro-Asiatic)',#'arabic',
    'hy': 'Other Indo-European',#'armenian',
    'az': 'Oghuz (Turkic)',#'azerbaijani',
    'eu': 'Isolate',#'basque',
    'be': 'Slavic (Indo-European)',#'belarusian',
    'bn': 'Indo-Aryan (Indo-European)',#'bengali',
    'bs': 'Slavic (Indo-European)',#'bosnian',
    'bg': 'Slavic (Indo-European)',#'bulgarian',
    'ca': 'Romance (Indo-European)',#'catalan',
    'ceb': 'Philippine (Austronesian)',#'cebuano',
    'ny': 'Bantu (Niger–Congo)',#'chichewa',
    'zh-cn': 'Sinitic (Sino-Tibetan)',#'chinese (simplified)',
    'zh-tw': 'Sinitic (Sino-Tibetan)',#'chinese (traditional)',
    'co': 'Romance (Indo-European)',#'corsican',
    'hr': 'Slavic (Indo-European)',#'croatian',
    'cs': 'Slavic (Indo-European)',#'czech',
    'da': 'Germanic (Indo-European)', #'danish',
    'nl': 'Germanic (Indo-European)', #'dutch',
    'en': 'Germanic (Indo-European)', #'english',
    'eo': 'Conlang',#'esperanto',
    'et': 'Finnic (Uralic)',#'estonian',
    'tl': 'Philippine (Austronesian)',#'filipino',
    'fi': 'Finnic (Uralic)',#'finnish',
    'fr': 'Romance (Indo-European)',#'french',
    'fy': 'Germanic (Indo-European)', #'frisian',
    'gl': 'Romance (Indo-European)',#'galician',
    'ka': 'Kartvelian',#'georgian',
    'de': 'Germanic (Indo-European)', #'german',
    'el': 'Other Indo-European', #'greek',
    'gu': 'Indo-Aryan (Indo-European)',#'gujarati',
    'ht': 'Romance (Indo-European)',#'haitian creole',
    'ha': 'Chadic (Afro-Asiatic)',#'hausa',
    'haw': 'Oceanic (Austronesian)',#'hawaiian',
    'iw': 'Semitic (Afro-Asiatic)',#'hebrew',
    'he': 'Semitic (Afro-Asiatic)',#'hebrew',
    'hi': 'Indo-Aryan (Indo-European)',#''hindi',
    'hmn': 'Hmong–Mien',#'hmong',
    'hu': 'Other Uralic',#'hungarian',
    'is': 'Germanic (Indo-European)', #'icelandic',
    'ig': 'Volta–Niger (Niger–Congo)',#'igbo',
    'id': 'Malayic (Austronesian)',#'indonesian',
    'ga': 'Celtic (Indo-European)',#'irish',
    'it': 'Romance (Indo-European)',#'italian',
    'ja': 'Isolate',#'japanese',
    'jw': 'Other Austronesian',#'javanese',
    'kn': 'Dravidian',#'kannada',
    'kk': 'Kipchak (Turkic)',#'kazakh',
    'km': 'Austroasiatic',#'khmer',
    'ko': 'Isolate',#'korean',
    'ku': 'Iranian (Indo-European)',#'kurdish (kurmanji)',
    'ky': 'Kipchak (Turkic)',#'kyrgyz',
    'lo': 'Kra–Dai',#'lao',
    'la': 'Romance (Indo-European)',#'latin',
    'lv': 'Baltic (Indo-European)',#'latvian',
    'lt': 'Baltic (Indo-European)',#'lithuanian',
    'lb': 'Germanic (Indo-European)', #'luxembourgish',
    'mk': 'Slavic (Indo-European)',#'macedonian',
    'mg': 'Other Austronesian',#'malagasy',
    'ms': 'Malayic (Austronesian)',#'malay',
    'ml': 'Dravidian',#'malayalam',
    'mt': 'Semitic (Afro-Asiatic)', #'maltese',
    'mi': 'Oceanic (Austronesian)',#'maori',
    'mr': 'Indo-Aryan (Indo-European)',#'marathi',
    'mn': 'Isolate',#'mongolian',
    'my': 'Burmish (Sino-Tibetan)',#'myanmar (burmese)',
    'ne': 'Indo-Aryan (Indo-European)',#'nepali',
    'no': 'Germanic (Indo-European)', #'norwegian',
    'or': 'Indo-Aryan (Indo-European)',#'odia',
    'ps': 'Iranian (Indo-European)',#'pashto',
    'fa': 'Iranian (Indo-European)',#'persian',
    'pl': 'Slavic (Indo-European)',#'polish',
    'pt': 'Romance (Indo-European)',#'portuguese',
    'pa': 'Indo-Aryan (Indo-European)',#'punjabi',
    'ro': 'Romance (Indo-European)',#'romanian',
    'ru': 'Slavic (Indo-European)',#'russian',
    'sm': 'Oceanic (Austronesian)',#'samoan',
    'gd': 'Celtic (Indo-European)',#'scots gaelic',
    'sr': 'Slavic (Indo-European)',#'serbian',
    'st': 'Bantu (Niger–Congo)',#'sesotho',
    'sn': 'Bantu (Niger–Congo)',#'shona',
    'sd': 'Indo-Aryan (Indo-European)',#'sindhi',
    'si': 'Indo-Aryan (Indo-European)',#'sinhala',
    'sk': 'Slavic (Indo-European)',#'slovak',
    'sl': 'Slavic (Indo-European)',#'slovenian',
    'so': 'Cushitic (Afro-Asiatic)',#'somali',
    'es': 'Romance (Indo-European)',#'spanish',
    'su': 'Other Austronesian',#'sundanese',
    'sw': 'Bantu (Niger–Congo)',#'swahili',
    'sv': 'Germanic (Indo-European)', #'swedish',
    'tg': 'Indo-Aryan (Indo-European)',#'tajik',
    'ta': 'Dravidian',#'tamil',
    'te': 'Dravidian',#''telugu',
    'th': 'Kra–Dai',#'thai',
    'tr': 'Oghuz (Turkic)',#'turkish',
    'uk': 'Slavic (Indo-European)',#'ukrainian',
    'ur': 'Indo-Aryan (Indo-European)',#'urdu',
    'ug': 'Karluk (Turkic)',#'uyghur',
    'uz': 'Karluk (Turkic)',#'uzbek',
    'vi': 'Austroasiatic',#'vietnamese',
    'cy': 'Celtic (Indo-European)',#'welsh',
    'xh': 'Bantu (Niger–Congo)',#''xhosa',
    'yi': 'Germanic (Indo-European)', #'yiddish',
    'yo': 'Volta–Niger (Niger–Congo)',#'yoruba',
    'zu': 'Bantu (Niger–Congo)',#'zulu',
}
# ruler: talks about colonial ruler of each language's nation-state
lang_ruler_dict_main = {
    'af': 'Britain', #'afrikaans',
    'sq': 'Ottomans', #'albanian',
    'am': 'Italy', #'amharic',
    'ar': 'Ottomans',#'arabic', 
    'hy': 'Russia',#'armenian',
    'az': 'Russia',#'azerbaijani',
    'eu': 'Spain',#'basque',
    'be': 'Russia',#'belarusian',
    'bn': 'Britain',#'bengali',
    'bs': 'Ottomans',#'bosnian',
    'bg': 'Ottomans',#'bulgarian',
    'ca': 'Spain',#'catalan',
    'ceb': 'Spain',#'cebuano',
    'ny': 'Britain', #chichewa',
    'zh-cn': 'China',#'chinese (simplified)',
    'zh-tw': 'China',#'chinese (traditional)',
    'co': 'France',#'corsican',
    'hr': 'Austria',#'croatian',
    'cs': 'Austria',#'czech',
    'da': 'Denmark', #'danish',
    'nl': 'Netherlands', #'dutch',
    'en': 'Britain', #'english',
    'eo': 'Poland',#'esperanto',
    'et': 'Russia',#'estonian',
    'tl': 'Spain',#'filipino',
    'fi': 'Russia',#'finnish',
    'fr': 'France',#'french',
    'fy': 'Netherlands', #'frisian',
    'gl': 'Spain',#'galician',
    'ka': 'Russia',#'georgian',
    'de': 'Germany', #'german',
    'el': 'Ottomans', #'greek',
    'gu': 'Britain',#'gujarati',
    'ht': 'France',#'haitian creole',
    'ha': 'Britain',#'hausa',
    'haw': 'United States',#'hawaiian',
    'iw': 'Britain',#'hebrew'
    'he': 'Britain',#'hebrew',
    'hi': 'Britain',#''hindi',
    'hmn': 'France',#'hmong',
    'hu': 'Austria',#'hungarian',
    'is': 'Denmark', #'icelandic',
    'ig': 'Britain',#'igbo',
    'id': 'Netherlands',#'indonesian',
    'ga': 'Britain',#'irish',
    'it': 'Italy',#'italian',
    'ja': 'Japan',#'japanese',
    'jw': 'Netherlands',#'javanese',
    'kn': 'Britain',#'kannada',
    'kk': 'Russia',#'kazakh',
    'km': 'France',#'khmer',
    'ko': 'Japan',#'korean',
    'ku': 'Ottomans',#'kurdish (kurmanji)',
    'ky': 'Russia',#'kyrgyz',
    'lo': 'France',#'lao',
    'la': 'Italy',#'latin',
    'lv': 'Russia',#'latvian',
    'lt': 'Russia',#'lithuanian',
    'lb': 'Germany', #'luxembourgish',
    'mk': 'Ottomans',#'macedonian',
    'mg': 'France',#'malagasy',
    'ms': 'Britain',#'malay',
    'ml': 'Britain',#'malayalam',
    'mt': 'Britain', #'maltese',
    'mi': 'Britain',#'maori',
    'mr': 'Britain',#'marathi',
    'mn': 'China',#'mongolian',
    'my': 'Britain',#'myanmar (burmese)',
    'ne': 'Britain',#'nepali',
    'no': 'Denmark', #'norwegian',
    'or': 'Britain',#'odia',
    'ps': 'Britain',#'pashto',
    'fa': 'Iran',#'persian',
    'pl': 'Russia',#'polish',
    'pt': 'Spain',#'portuguese',
    'pa': 'Britain',#'punjabi',
    'ro': 'Ottomans',#'romanian',
    'ru': 'Russia',#'russian',
    'sm': 'United States',#'samoan',
    'gd': 'Britain',#'scots gaelic',
    'sr': 'Ottomans',#'serbian',
    'st': 'Britain',#'sesotho',
    'sn': 'Britain',#'shona',
    'sd': 'Britain',#'sindhi',
    'si': 'Britain',#'sinhala',
    'sk': 'Austria',#'slovak',
    'sl': 'Austria',#'slovenian',
    'so': 'Italy',#'somali',
    'es': 'Spain',#'spanish',
    'su': 'Netherlands',#'sundanese',
    'sw': 'Britain',#'swahili',
    'sv': 'Denmark', #'swedish',
    'tg': 'Russia',#'tajik',
    'ta': 'Britain',#'tamil',
    'te': 'Britain',#''telugu',
    'th': 'Thailand',#'thai',
    'tr': 'Ottomans',#'turkish',
    'uk': 'Russia',#'ukrainian',
    'ur': 'Britain',#'urdu',
    'ug': 'China',#'uyghur',
    'uz': 'Russia',#'uzbek',
    'vi': 'France',#'vietnamese',
    'cy': 'Britain',#'welsh',
    'xh': 'Britain',#''xhosa',
    'yi': 'Poland', #'yiddish',
    'yo': 'Britain',#'yoruba',
    'zu': 'Britain',#'zulu',
}